fix: id:50158 changes in accordion component for fulfill accessibility
emgage/engage-ui pull request #625
Opened 2021-01-22 10:21 UTC by Farhan-emgage

changes in accordion component for fulfill accessibility

2021-01-22 10:21 UTC, emgageadmin commented
https://atera.tpondemand.com/entity/50158

2021-01-22 17:29 UTC, weegrom requested changes

2021-01-22 17:29 UTC, weegrom commented on src/components/Accordion/Accordion.scss
> +    color: #212121;
@Farhan-emgage this should use the Heading or DisplayText component and not require custom styling.

2021-01-22 17:29 UTC, weegrom commented on src/components/Accordion/AccordionItem.tsx
>            {header}
@Farhan-emgage this should use the Heading or DisplayText component.

2021-01-28 22:56 UTC, weegrom commented
@Farhan-emgage looks like this is still waiting on the requested changes.

2021-01-29 02:06 UTC, Farhan-emgage commented
Actually for this discussion we suppose to arranged meeting (which was cancel due to my son health).

2021-04-20 16:39 UTC, closed without merging