fix: id:55538 long description name warped in table
emgage/engage-ui pull request #979
Opened 2021-11-08 01:56 UTC by Farhan-emgage

long description name warped in table

2021-11-08 01:56 UTC, emgageadmin commented
https://atera.tpondemand.com/entity/55538

2021-11-08 15:14 UTC, weegrom requested changes

2021-11-08 15:14 UTC, weegrom commented on src/components/Table/Table.scss
> +      word-break: break-all;
@Farhan-emgage I don't think this will work, as it will even break small words instead of wrapping them. Try overflow-wrap: break-word;

2021-11-09 15:02 UTC, weegrom approved these changes

2021-11-09 15:02 UTC, merged